### ISSUE TITLE
If a list item ends with a link with special attributes, the special attributes are applied to the list item, not to the link

### ISSUE THREAD

**Issue by douyo** [kjdev/hoextdown#43]
If you have a list item that ends with a link that has a special attribute:

*   list item with [link](https://google.com){target="_blank"}

The markdown processor applies the special attribute to the list item, not to the link.

<li target="_blank">list item with <a href="https://google.com">link</a></li>

There should be a clear way to indicate whether you want the special attribute applied to the link vs. the list item.

**Comment by kjdev** [comment]
Please use the external reference link if you want to explicitly give the link special attributes in the list

```
- list item with [link]

[link]: url "optional title" {target="_blank"}
```

**Comment by douyo** [comment]
Ah, OK, thanks!  That does work.
